version: 2.1

jobs:
  deploy:
    docker:
      - image: google/cloud-sdk
    working_directory: /tmp/workspace
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run:
          name: Copy across app.yaml config
          command: ./app.yaml.sh > ./app.yaml
      - run:
        name: Set up gcloud config
        command: |
          echo $GCLOUD_KEY | base64 --decode | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project ${GCLOUD_PROJECT}
          gcloud --quiet config set compute/zone europe-west2
      - deploy:
          name: Deploying to App Engine
          command: gcloud app deploy app.yaml cron.yaml

workflows:
  deploy:
    jobs:
      - deploy:
        name: deploy-staging
        filters:
          branches:
            only: master
      - approve-prod-deployment:
          type: approval
          requires:
            - deploy-staging
      - deploy:
          name: deploy-prod
          context: "SHE Choir Production"
          requires:
            - approve-prod-deployment
